# Generated by Django 2.2.8 on 2020-08-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MyTrips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(choices=[('IITG', 'IITG'), ('RAILWAY STATION GUWAHATI', 'RAILWAY STATION GUWAHATI'), ('RAILWAY STATION KAMAKHYA', 'RAILWAY STATION KAMAKHYA'), ('AIRPORT', 'AIRPORT')], max_length=50)),
                ('dest', models.CharField(choices=[('IITG', 'IITG'), ('RAILWAY STATION GUWAHATI', 'RAILWAY STATION GUWAHATI'), ('RAILWAY STATION KAMAKHYA', 'RAILWAY STATION KAMAKHYA'), ('AIRPORT', 'AIRPORT')], max_length=50)),
                ('organizer', models.CharField(max_length=50)),
                ('journey_date', models.DateTimeField()),
            ],
        ),
    ]
