# Generated by Django 2.2.8 on 2020-08-06 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='jouney_date',
            new_name='journey_date',
        ),
    ]
